Prac\MentBundle\Entity\Skill:
  type: entity
  table: skill
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    name:
      type: string
      length: 255
      unique: true
  oneToMany:
    user_skills:
      targetEntity: UserSkill
      mappedBy: skill
  lifecycleCallbacks:
    prePersist: [ setCreatedAtValue ]
